# Generated by Django 5.2.5 on 2026-03-28 01:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UltimaAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo_veiculo', models.CharField(choices=[('LEVE', 'Leve'), ('MEDIO', 'Médio'), ('PESADO', 'Pesado'), ('EQUIPAMENTO', 'Equipamento')], default='LEVE', max_length=20)),
                ('segmento', models.CharField(choices=[('LT', 'Linha de Transmissão'), ('SE', 'Subestação'), ('N/A', 'Não Aplicável')], default='N/A', max_length=5)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Em Manutenção', 'Em Manutenção'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=20)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='frota.departamento')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='frota.modeloveiculo')),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='frota.regional')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos', models.TextField()),
                ('nome_oficina', models.CharField(blank=True, max_length=100, verbose_name='Nome da Oficina')),
                ('cidade_oficina', models.CharField(blank=True, max_length=100, verbose_name='Cidade da Oficina')),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('data_previsao_saida', models.DateField(blank=True, null=True)),
                ('numero_os', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da OS/Ticket')),
                ('status_os', models.CharField(choices=[('Aguardando Orçamento', 'Aguardando Orçamento'), ('Aguardando Aprovação', 'Aguardando Aprovação'), ('Aprovado', 'Aprovado'), ('Garantia', 'Garantia'), ('N/A', 'N/A')], max_length=50, verbose_name='Status da OS')),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manutencao', to='frota.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Indisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidade', to='frota.veiculo')),
            ],
        ),
    ]
